name: CI (Lint • Test • Build • Visual Regression)
run-name: CI • ${{ github.ref_name }} • ${{ github.actor }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: 17.x

jobs:
  #  1. Linting
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint TypeScript
        run: npm run lint:ts

      - name: Lint CSS
        run: npm run lint:css

  #  2. Tests
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test:unit

  #  3. Build and visual regression tests
  build_and_test_ui:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build production project
        run: npm run build:prod

      - name: Build storybook
        run: npm run storybook:build

      - name: Run visual regression tests
        run: npm run test:ui:ci


# Job order:
#   1.Install
#   2.Lint
#   3.Tests
#   4.Build
#   5.Visual regression tests